package com.cs.bank.entity;

import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Column;

import java.math.BigDecimal;
import java.time.LocalDate;

@Entity // Marks the class as a JPA entity
public class Loan {

    @Id // Specifies the primary key
    @GeneratedValue(strategy = GenerationType.IDENTITY) // Configures the primary key to be auto-generated by the database
    @Column(name = "loan_id")
    private Integer loanID;

    // VARCHAR(20) is typically mapped to a String in Java
    @Column(name = "loan_type", length = 20, nullable = false)
    private String loanType;

    // DECIMAL(10, 2) is best mapped to BigDecimal for precise financial calculations
    @Column(name = "loan_amount", precision = 10, scale = 2, nullable = false)
    private BigDecimal loanAmount;

    // DECIMAL(10, 2) is best mapped to BigDecimal
    @Column(name = "interest_rate", precision = 10, scale = 2, nullable = false)
    private BigDecimal interestRate;

    // INTEGER is mapped to Integer/int
    @Column(name = "term_months", nullable = false)
    private Integer term;

    // DATE is mapped to java.time.LocalDate
    @Column(name = "start_date", nullable = false)
    private LocalDate startDate;

    // DATE is mapped to java.time.LocalDate
    @Column(name = "end_date")
    private LocalDate endDate;

    // VARCHAR(20) is typically mapped to a String
    @Column(name = "status", length = 20, nullable = false)
    private String status;

    // Note: The relationship to 'Customer' is omitted as requested by Note #1.

    /**
     * Default constructor required by JPA.
     */
    public Loan() {
    }

    /**
     * Parameterized constructor for convenience.
     */
    public Loan(String loanType, BigDecimal loanAmount, BigDecimal interestRate, Integer term, LocalDate startDate, LocalDate endDate, String status) {
        this.loanType = loanType;
        this.loanAmount = loanAmount;
        this.interestRate = interestRate;
        this.term = term;
        this.startDate = startDate;
        this.endDate = endDate;
        this.status = status;
    }

    // --- Getters and Setters ---

    public Integer getLoanID() {
        return loanID;
    }

    // Setters for the primary key are often omitted or kept protected/private
    // if the key is exclusively generated by the database.
    // public void setLoanID(Integer loanID) {
    //     this.loanID = loanID;
    // }

    public String getLoanType() {
        return loanType;
    }

    public void setLoanType(String loanType) {
        this.loanType = loanType;
    }

    public BigDecimal getLoanAmount() {
        return loanAmount;
    }

    public void setLoanAmount(BigDecimal loanAmount) {
        this.loanAmount = loanAmount;
    }

    public BigDecimal getInterestRate() {
        return interestRate;
    }

    public void setInterestRate(BigDecimal interestRate) {
        this.interestRate = interestRate;
    }

    public Integer getTerm() {
        return term;
    }

    public void setTerm(Integer term) {
        this.term = term;
    }

    public LocalDate getStartDate() {
        return startDate;
    }

    public void setStartDate(LocalDate startDate) {
        this.startDate = startDate;
    }

    public LocalDate getEndDate() {
        return endDate;
    }

    public void setEndDate(LocalDate endDate) {
        this.endDate = endDate;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    @Override
    public String toString() {
        return "Loan{" +
                "loanID=" + loanID +
                ", loanType='" + loanType + '\'' +
                ", loanAmount=" + loanAmount +
                ", interestRate=" + interestRate +
                ", term=" + term +
                ", startDate=" + startDate +
                ", endDate=" + endDate +
                ", status='" + status + '\'' +
                '}';
    }
}