package com.cs.bank.entity;

import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Column;

import java.math.BigDecimal;
import java.time.LocalDate;

@Entity // Marks the class as a JPA entity
public class LoanPayment {

    @Id // Specifies the primary key
    @GeneratedValue(strategy = GenerationType.IDENTITY) // Configures the primary key to be auto-generated
    @Column(name = "loan_payment_id")
    private Integer loanPaymentID;

    // DATE is mapped to java.time.LocalDate
    @Column(name = "scheduled_payment_date", nullable = false)
    private LocalDate scheduledPaymentDate;

    // DECIMAL(10, 2) is mapped to BigDecimal for precision
    @Column(name = "payment_amount", precision = 10, scale = 2, nullable = false)
    private BigDecimal paymentAmount;

    // DECIMAL(10, 2) is mapped to BigDecimal
    @Column(name = "principal_amount", precision = 10, scale = 2, nullable = false)
    private BigDecimal principalAmount;

    // DECIMAL(10, 2) is mapped to BigDecimal
    @Column(name = "interest_amount", precision = 10, scale = 2, nullable = false)
    private BigDecimal interestAmount;

    // DECIMAL(10, 2) is mapped to BigDecimal
    @Column(name = "paid_amount", precision = 10, scale = 2)
    private BigDecimal paidAmount;

    // DATE is mapped to java.time.LocalDate. It is nullable (not mandatory).
    @Column(name = "paid_date")
    private LocalDate paidDate;


    /**
     * Default constructor required by JPA.
     */
    public LoanPayment() {
    }

    // --- Getters and Setters ---

    public Integer getLoanPaymentID() {
        return loanPaymentID;
    }

    // Setter for the primary key is often omitted if generated by the DB.
    // public void setLoanPaymentID(Integer loanPaymentID) {
    //     this.loanPaymentID = loanPaymentID;
    // }

    public LocalDate getScheduledPaymentDate() {
        return scheduledPaymentDate;
    }

    public void setScheduledPaymentDate(LocalDate scheduledPaymentDate) {
        this.scheduledPaymentDate = scheduledPaymentDate;
    }

    public BigDecimal getPaymentAmount() {
        return paymentAmount;
    }

    public void setPaymentAmount(BigDecimal paymentAmount) {
        this.paymentAmount = paymentAmount;
    }

    public BigDecimal getPrincipalAmount() {
        return principalAmount;
    }

    public void setPrincipalAmount(BigDecimal principalAmount) {
        this.principalAmount = principalAmount;
    }

    public BigDecimal getInterestAmount() {
        return interestAmount;
    }

    public void setInterestAmount(BigDecimal interestAmount) {
        this.interestAmount = interestAmount;
    }

    public BigDecimal getPaidAmount() {
        return paidAmount;
    }

    public void setPaidAmount(BigDecimal paidAmount) {
        this.paidAmount = paidAmount;
    }

    public LocalDate getPaidDate() {
        return paidDate;
    }

    public void setPaidDate(LocalDate paidDate) {
        this.paidDate = paidDate;
    }
}